# Generated by Django 5.2.10 on 2026-02-07 12:45

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimage_is_main'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel', primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif / visible')),
                ('products', models.ManyToManyField(related_name='wishlisted_by', to='product.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'liste de souhaits',
                'verbose_name_plural': 'listes de souhaits',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
