# Generated by Django 5.2.10 on 2026-02-15 06:40

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order_payment_id_order_payment_status_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universal unique identifier', primary_key=True, serialize=False, verbose_name='Identifier')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active / visible')),
                ('name', models.CharField(max_length=200, verbose_name='promotion name')),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universal unique identifier', primary_key=True, serialize=False, verbose_name='Identifier')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active / visible')),
                ('promotion_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('special_label', models.CharField(blank=True, help_text='Ex: Flash Sale, -50%, etc.', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_items', to='product.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.promotion')),
            ],
            options={
                'verbose_name': 'promotion item',
                'verbose_name_plural': 'promotion items',
                'ordering': ['-created'],
                'abstract': False,
                'unique_together': {('promotion', 'product')},
            },
        ),
    ]
