# Generated by Django 5.2.10 on 2026-02-13 20:16

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel', primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif / visible')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('content', models.TextField(help_text='Contenu au format HTML ou texte brut', verbose_name='contenu')),
            ],
            options={
                'verbose_name': 'page légale',
                'verbose_name_plural': 'pages légales',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
