# Generated by Django 5.2.10 on 2026-02-13 20:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalpage',
            options={'ordering': ['-created'], 'verbose_name': 'legal page', 'verbose_name_plural': 'legal pages'},
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='content',
            field=models.TextField(help_text='Content in HTML or raw text format', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universal unique identifier', primary_key=True, serialize=False, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active / visible'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
