# Generated by Django 5.2.10 on 2026-02-26 14:37

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_legalpage_options_alter_legalpage_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universal unique identifier', primary_key=True, serialize=False, verbose_name='Identifier')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active / visible')),
                ('title', models.CharField(default='Privacy Policy', max_length=200, verbose_name='title')),
                ('content', models.TextField(default="\n# Privacy Policy\nLast Updated: February 26, 2026\n\nAt BBP Collection, we are committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your personal information when you visit our website or make a purchase.\n\n## 1. Information We Collect\nWe collect information you provide directly to us, such as your name, email address, shipping address, and payment information (processed securely through Stripe). We also collect automated data about your device and browsing activity via cookies.\n\n## 2. How We Use Your Information\nWe use your data to:\n- Process and fulfill your orders.\n- Communicate with you about your purchases and promotional offers.\n- Improve our website and customer experience.\n- Comply with legal obligations and prevent fraud.\n\n## 3. Data Protection\nWe implement industry-standard security measures to protect your personal data. However, no method of transmission over the Internet is 100% secure.\n\n## 4. Third-Party Services\nWe share information with third-party providers only as necessary to provide our services, such as Stripe for payment processing and shipping carriers. These providers have their own privacy policies.\n\n## 5. Your Rights (CCPA/GDPR)\nDepending on your residency, you may have rights to access, update, or delete your personal information. Contact us at the email below for requests.\n\n## 6. Children's Privacy\nOur website is not intended for children under 13. We do not knowingly collect data from children (COPPA Compliance).\n\n## 7. Changes to This Policy\nWe may update this policy from time to time. Changes will be posted on this page with an updated date.\n\n## 8. Contact Us\nIf you have questions about this Privacy Policy, please contact us at:\nEmail: support@bbpcollection.com\n", verbose_name='content')),
            ],
            options={
                'verbose_name': 'privacy policy',
                'verbose_name_plural': 'privacy policy',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
