# Generated by Django 5.2.10 on 2026-03-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_privacypolicy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
    ]
